### PR TITLE
Update google-api-client to 0.9

### PR DESCRIPTION
**Pull request by atz**
This is required for rails 5+ support, because `0.8` series of the gem are limited to `activesupport` <5.  In the `0.9` series, the dependency on `activesupport` is removed entirely, freeing downstream consumers to use whatever version they wish.

### CODE REVIEW

**Comment by atz** [comment]
I obviously don't care about -0.08% coverage drop from removing code.

**Comment by atz** [comment]
This would have been useful to discover earlier, but it is informative:
https://developers.google.com/drive/v3/web/migration

**Comment by atz** [comment]
So I got it to this point:

screen shot 2016-09-10 at 1 22 20 am


With populated date field.

Outstanding issues:

- For Google Drive, the AJAX/treeview does not update when filename or arrow/toggle is clicked.  The query completes fine on the back end and returns results, but despite displaying "100%" the browser does not render them.
- No back or "up" navigation, no way to exit a folder

**Comment by atz** [comment]
I dislike the model of returning HTML partials as their own HTTP resource.  We should be returning JSON and rendering the data on the client side into the table form.

**Comment by atz** [comment]
OK, got listings fully functional.  Only final retrieval outstanding.

screen shot 2016-09-27 at 4 06 24 pm

**Comment by atz** [comment]
Note, there is apparently a longstanding bug in `FileEntry` that labels everything a directory, as shows in the screenshots.  Should be fixed here.

**Comment by mbklein** [comment]
:+1: This looks great, @atz. Thanks for putting in all the work. I'm going to merge, but hold off cutting a release until I* get a chance to do a manual test with a couple of the other providers.

* or anyone

**Comment by emanuil-tolev** [comment]
This blocks using sufia 7.2.0 with Rails 5, so would be very interested to see a new release esp. considering the code's in already :). This is a new instance so I'm keen to see if it can be upgraded 

I'm not sure I can help that much with testing it though so it may be easier for whoever has already done it in the past to do it... The bit I can't see how to do is how do I get "sufia ~> 7.2.0", but with browse-everything "tip of master" rather than sufia's usual dependency "browse-everything ~> 0.10.3"?

**Comment by emanuil-tolev** [comment]
Sorry, should have commented on related issue - deleted to move conversation to #131 .

**Comment by scherztc** [comment]
@atz Were you ever able to retrieve a file from google drive using the 0.9.x google-api-client?

**Pull request merged**
